export enum ExecCommands {
	runCommand = "save-commands.runCommand",
	addCommand = "save-commands.addCommand",
	deleteCommands = "save-commands.deleteCommands",
	deleteCommand = "save-commands.deleteCommand",
	editCommand = "save-commands.editCommand",
	copyCommand = "save-commands.copyCommand",
	runCommandInActiveTerminal = "save-commands.runCommandInActiveTerminal",
	reset = "save-commands.reset",
	refreshView = "save-commands.refreshView",
	addFolder = "save-commands.addFolder",
	deleteFolder = "save-commands.deleteFolder",
	editFolder = "save-commands.editFolder",
	runFolder = "save-commands.runFolder",
	runFolderInActiveTerminal = "save-commands.runFolderInActiveTerminal",
	openConfigFile = "save-commands.openConfigFile",
	openGlobalConfigFile = "save-commands.openGlobalConfigFile",
	sshConnect = "save-commands.sshConnect",
	sshConnectInActiveTerminal = "save-commands.sshConnectInActiveTerminal",
	addSshConnection = "save-commands.addSshConnection",
	deleteSshConnection = "save-commands.deleteSshConnection",
	openSshConfigFile = "save-commands.openSshConfigFile",
	openGlobalSshConfigFile = "save-commands.openGlobalSshConfigFile",
	editSshConnection = "save-commands.editSshConnection",
}
